#!/bin/sh
### BEGIN INIT INFO
# Provides: aria2
# Required-Start: $remote_fs $network
# Required-Stop: $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Aria2 Downloader
### END INIT INFO
 
case "$1" in
start)
 
 echo -n "Starting Aria2c"
 sudo -u root bash /root/.aria2/updatetracker.sh
 aria2c --conf-path=/root/.aria2/aria2.conf -D
;;
stop)
 
 echo -n "Killing Aria2c"
 killall aria2c
;;
restart)
 echo -n "Restarting Aria2c"
 killall aria2c
 sudo -u root bash /root/.aria2/updatetracker.sh
aria2c --conf-path=/root/.aria2/aria2.conf -D
;;
esac
exit
