#!/bin/bash
# 下载AriaNg
sudo rm -rf /tmp/Onekey-deploy_aria2
sudo git clone https://github.com/Masterchiefm/Onekey-deploy_aria2.git /tmp/Onekey-deploy_aria2
sudo rm -rf /var/www/html/lixian
sudo mkdir -p /var/www/html/lixian 
sudo unzip /tmp/Onekey-deploy_aria2/*.zip -d /var/www/html/lixian
sudo chmod 777 -R /var/www/html/lixian
#添加启动入口
sudo rm -rf ~/Start_Aria.sh
sudo cp /tmp/Onekey-deploy_aria2/Start* ~/
sudo chmod 777 ~/Start_Aria.sh
sudo rm -rf /root/Start_Aria.sh
sudo cp /tmp/Onekey-deploy_aria2/Start* /root
sudo chmod 777 /root/Start_Aria.sh
#配置密码
sudo sh ./setpasswd





