#!/bin/bash
#修改conf，设置RPC密码
sudo rm -rf /root/.aria2
sudo mkdir -p /root/.aria2
sudo rm -rf /root/.aria2/*
sudo touch /root/.aria2/aria2.session
sudo mv /tmp/Onekey-deploy_aria2/aria2.conf /root/.aria2/
sudo mv /tmp/Onekey-deploy_aria2/updatetracker.sh /root/.aria2/
sudo rm -rf ./install.sh
clear

echo "请输入你想设置的RPC登录密码"
read password
words1=已将RPC密码设置为:
echo $words1 $password
secret=rpc-secret=$password
sudo echo $secret >> /root/.aria2/aria2.conf
echo RPC密码配置成功，请记住密码是：
echo $password
echo 配置文件保存在 /root/.aria2/aria2.conf 中
echo 以后要修改密码，请 vim /root/.aria2/aria2.conf 修改最后一行的 rpc-secret=
echo 按任意键结束
read a
clear
cat /tmp/Onekey-deploy_aria2/README.md
echo 请再次阅读上述内容

